"""Build shopping lists from BOM CSVs, one section per job.

Usage:  python scripts/build_shopping_list.py [model]
        (no argument = every *-bom.csv in quad-upgrade/data)

  verified    -> listed as confirmed
  unverified  -> listed, marked PROVISIONAL (single source — check your board first)
  conflict    -> not listed as a part; shown under "Needs resolving"
  template    -> ignored except for a count
"""
import csv
import sys
from collections import defaultdict
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "quad-upgrade" / "data"
REQUIRED = ["ref", "replacement_value", "qty", "source"]
STATUSES = {"template", "unverified", "verified", "conflict"}
VARIANTS = ["<8000", ">=8000"]


def job_key(r):
    if r["category"] == "restoration":
        return [f"restoration (serial {v})" for v in VARIANTS
                if r["variant"] in (v, "all")]
    return [r["category"]]


def build(bom_path: Path) -> int:
    model = bom_path.stem.replace("-bom", "")
    rows = list(csv.DictReader(bom_path.open(newline="", encoding="utf-8")))
    errors, jobs, conflicts, templates = [], defaultdict(list), [], 0

    for n, r in enumerate(rows, start=2):
        status = r.get("status", "").strip()
        if status not in STATUSES:
            errors.append(f"line {n}: unknown status '{status}'")
            continue
        if status == "template":
            templates += 1
            continue
        if status == "conflict":
            conflicts.append(r)
            continue
        missing = [f for f in REQUIRED if not r.get(f, "").strip() or "TODO" in r[f]]
        if missing:
            errors.append(f"line {n} ({r['ref']}): missing {', '.join(missing)}")
            continue
        if not r["qty"].isdigit():
            errors.append(f"line {n} ({r['ref']}): qty is not a whole number")
            continue
        for key in job_key(r):
            jobs[key].append(r)

    out = [f"# {model} — shopping lists", "",
           "_Generated by `scripts/build_shopping_list.py` from the BOM. Do not edit by hand._", "",
           "**PROVISIONAL** = taken from one source and not yet checked against a board. "
           "Confirm each value on your own unit before ordering.", ""]
    for key in sorted(jobs, key=lambda k: (not k.startswith("restoration"), k)):
        out += [f"## {key}", "",
                "| Ref | Replacement | Type | Qty | Supplier | Status | Source | Notes |",
                "|---|---|---|---|---|---|---|---|"]
        for r in jobs[key]:
            status = "confirmed" if r["status"] == "verified" else "PROVISIONAL"
            part = r["replacement_part"] or r["replacement_value"]
            out.append(f"| {r['ref']} | {part} | {r['replacement_type']} | {r['qty']} | "
                       f"{r['supplier']} | {status} | {r['source']} | {r['notes']} |")
        out.append("")
    if conflicts:
        out += ["## Needs resolving (sources disagree — do not order yet)", "",
                "| Ref | Options | Source | Notes |", "|---|---|---|---|"]
        for r in conflicts:
            out.append(f"| {r['ref']} | {r['replacement_value']} | {r['source']} | {r['notes']} |")
        out.append("")
    if templates:
        out += [f"_{templates} template row(s) not yet filled in._", ""]

    (DATA / f"{model}-shopping-list.md").write_text("\n".join(out), encoding="utf-8")
    print(f"{model}: {sum(len(v) for v in jobs.values())} list entries across {len(jobs)} jobs, "
          f"{len(conflicts)} conflicts, {len(errors)} errors")
    for e in errors:
        print("  ERROR", e)
    return len(errors)


if __name__ == "__main__":
    targets = ([DATA / f"{sys.argv[1]}-bom.csv"] if len(sys.argv) > 1
               else sorted(DATA.glob("*-bom.csv")))
    sys.exit(1 if sum(build(p) for p in targets) else 0)
