"""Build shopping lists from BOM CSVs, one section per job.

Run from the repository root:
        Windows: py -3 scripts/build_shopping_list.py [model] [--check]
        macOS/Linux: python3 scripts/build_shopping_list.py [model] [--check]
        (no argument = every *-bom.csv in quad-upgrade/data)

  verified    -> listed as confirmed
  unverified  -> listed, marked PROVISIONAL (not physically checked against a board)
  conflict    -> not listed as a part; shown under "Needs resolving"
  template    -> ignored except for a count
"""
import csv
import argparse
import sys
from collections import defaultdict
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "quad-upgrade" / "data"
REQUIRED_COLUMNS = {
    "model", "variant", "board", "ref", "replacement_value", "replacement_type",
    "qty", "category", "status", "source",
}
REQUIRED = ["ref", "replacement_value", "qty", "source"]
STATUSES = {"template", "unverified", "verified", "conflict"}


def variant_label(variant):
    """Serial ranges read as 'serial <=8000'; named variants such as 'MKI' stand alone."""
    return f"serial {variant}" if variant[:1] in "<>0123456789" else variant


def job_key(r, variants):
    if r["category"] == "restoration":
        return [f"restoration ({variant_label(v)})" for v in variants
                if r["variant"] in (v, "all")]
    if r["variant"] in variants:
        return [f"{r['category']} ({variant_label(r['variant'])})"]
    return [r["category"]]


def table_cell(value: str) -> str:
    """Keep user-supplied BOM text from breaking generated Markdown tables."""
    return value.replace("|", "\\|").replace("\r", " ").replace("\n", " ").strip()


def render(bom_path: Path):
    model = bom_path.stem.replace("-bom", "")
    with bom_path.open(newline="", encoding="utf-8-sig") as stream:
        reader = csv.DictReader(stream)
        columns = set(reader.fieldnames or [])
        rows = list(reader)
    errors = []
    missing_columns = sorted(REQUIRED_COLUMNS - columns)
    if missing_columns:
        errors.append(f"missing required columns: {', '.join(missing_columns)}")
        return "", errors, 0, 0

    variants = list(dict.fromkeys(
        r["variant"].strip() for r in rows
        if r.get("category", "").strip() == "restoration"
        and r.get("variant", "").strip() not in ("", "all")
    ))
    errors, jobs, conflicts, templates = [], defaultdict(list), [], 0

    for n, r in enumerate(rows, start=2):
        status = (r.get("status") or "").strip()
        if status not in STATUSES:
            errors.append(f"line {n}: unknown status '{status}'")
            continue
        if status == "template":
            templates += 1
            continue
        category = (r.get("category") or "").strip()
        variant = (r.get("variant") or "").strip()
        if not category:
            errors.append(f"line {n}: missing category")
            continue
        if category == "restoration" and variant not in (*variants, "all"):
            errors.append(f"line {n}: unknown restoration variant '{variant}'")
            continue
        missing = [f for f in REQUIRED if not (r.get(f) or "").strip()]
        if missing:
            errors.append(f"line {n} ({r.get('ref', '?')}): missing {', '.join(missing)}")
            continue
        if status != "conflict" and any("TODO" in (r.get(f) or "") for f in ("replacement_value",)):
            errors.append(f"line {n} ({r['ref']}): replacement value is still TODO")
            continue
        if not (r.get("qty") or "").strip().isdigit():
            errors.append(f"line {n} ({r['ref']}): qty is not a whole number")
            continue
        if status == "conflict":
            conflicts.append(r)
            continue
        for key in job_key(r, variants):
            jobs[key].append(r)

    out = [f"# {model} — shopping lists", "",
           "_Generated by `scripts/build_shopping_list.py` from the BOM. Do not edit by hand._", "",
           "**PROVISIONAL** = not yet checked against a physical board. "
           "Have a competent restorer verify applicable parts against the fitted board before ordering.", "",
           "**Safety:** If you are new to electronics or unsure how to work safely inside mains equipment, "
           "use this list for planning only. Do not open the unit or make internal measurements; have a "
           "qualified technician handle internal checks, restoration work and first power-up. See "
           "[safety guidance](../reference/safety.md).", ""]
    for key in sorted(jobs, key=lambda k: (not k.startswith("restoration"), k)):
        out += [f"## {key}", "",
                "| Ref | Replacement | Type | Qty | Supplier | Status | Source | Notes |",
                "|---|---|---|---|---|---|---|---|"]
        for r in jobs[key]:
            status = "confirmed" if r["status"] == "verified" else "PROVISIONAL"
            part = r["replacement_part"] or r["replacement_value"]
            cells = [r["ref"], part, r["replacement_type"], r["qty"], r["supplier"],
                     status, r["source"], r["notes"]]
            out.append("| " + " | ".join(table_cell(value or "") for value in cells) + " |")
        out.append("")
    if conflicts:
        out += ["## Needs resolving (sources disagree — do not order yet)", "",
                "| Job | Variant | Ref | Options | Source | Notes |",
                "|---|---|---|---|---|---|"]
        for r in conflicts:
            cells = [r["category"], r["variant"], r["ref"], r["replacement_value"],
                     r["source"], r["notes"]]
            out.append("| " + " | ".join(table_cell(value or "") for value in cells) + " |")
        out.append("")
    if templates:
        out += [f"_{templates} template row(s) not yet filled in._", ""]

    return "\n".join(out), errors, sum(len(v) for v in jobs.values()), len(conflicts)


def build(bom_path: Path, check: bool = False) -> int:
    model = bom_path.stem.replace("-bom", "")
    output, errors, entries, conflicts = render(bom_path)
    destination = DATA / f"{model}-shopping-list.md"
    if not errors:
        if check:
            if not destination.exists() or destination.read_text(encoding="utf-8") != output:
                errors.append(f"{destination.name} is stale; run scripts/build_shopping_list.py")
        else:
            destination.write_text(output, encoding="utf-8")
    print(f"{model}: {entries} list entries, {conflicts} conflicts, {len(errors)} errors")
    for e in errors:
        print("  ERROR", e)
    return len(errors)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("model", nargs="?", help="model slug, for example quad-34")
    parser.add_argument("--check", action="store_true",
                        help="fail if a generated shopping list is missing or stale")
    args = parser.parse_args()
    targets = ([DATA / f"{args.model}-bom.csv"] if args.model
               else sorted(DATA.glob("*-bom.csv")))
    missing = [p for p in targets if not p.exists()]
    for path in missing:
        print(f"ERROR: BOM not found: {path}")
    sys.exit(1 if missing or sum(build(p, check=args.check) for p in targets) else 0)
